ALTER TABLE `webcal_user` 
ADD `role_id` TINYINT NULL,
ADD `site_id` TINYINT NULL,
ADD `count` INT NULL,
ADD `age_range` VARCHAR(10) NULL,
ADD `qualifications` VARCHAR(255) NULL,
ADD `notes` VARCHAR(255) NULL,
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL,
ADD `no_email` CHAR( 1 ) NULL,
ADD `is_contacted` CHAR( 1 ) NULL;

ALTER TABLE `webcal_entry` 
ADD `job_id` TINYINT NULL, 
ADD `person_need` TINYINT NULL DEFAULT '0',
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `webcal_entry_user`
ADD `count` INT NULL,
ADD `notes` VARCHAR(255) NULL,
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL,
CHANGE `cal_percent` `cal_percent` INT( 11 ) NULL DEFAULT NULL;

ALTER TABLE `webcal_config` 
DROP PRIMARY KEY;

--

ALTER TABLE `area`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `days`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `district`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `group`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `job`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `jobcategory`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `qualification`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `role`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `site`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `subcamp`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `user_jobcategory`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;

ALTER TABLE `user_qualification`
ADD `def_date` TIMESTAMP NULL,
ADD `def_user` VARCHAR(25) NULL,
ADD `upd_date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD `upd_user` VARCHAR(25) NULL;